### ISSUE TITLE
error running macro

### ISSUE THREAD

**Issue by cristianmtr** [saif-ellafi/foundryvtt-mythic-gme#5]
I imported the Random Event macro but when I try to run it, I get:

```
mythic-gme-tools.js:443 Uncaught (in promise) TypeError: Cannot read property 'timeBeforeHide' of undefined
    at Function._mgmeSubmitOracleQuestion (mythic-gme-tools.js:443)
```

**Comment by saif-ellafi** [comment]
Hi @cristianmtr - sorry about that! `timeBeforeHide` has to do with 3D Dice. Do you have Dice so Nice installed?

**Comment by saif-ellafi** [comment]
Ah, @cristianmtr - this seems to be happening on 0.8.9 -- I will see if I can support  both V9 and 0.8.x at the same time.

Do you intend on upgrading anytime soon?

**Comment by saif-ellafi** [comment]
ahhh no, the error is something else @cristianmtr - I think this is because there is a part in Random Event that does not check if your Dice so Nice 3D Dice settings were ever configured. If you go to Dice so Nice settings and press Save, it should work

Go here:

![Screenshot_20211229_213129](https://user-images.githubusercontent.com/27952699/147701137-d3272aa7-dbc9-4af7-aaa0-409235228ffe.png)

Then here and press "Save" on all menus!

![image](https://user-images.githubusercontent.com/27952699/147701124-a13dd986-2fb3-47a3-a00f-1247afa5147a.png)

**Comment by saif-ellafi** [comment]
The fix to prevent this error should be now addressed with a proper error. Have fun!
