### ISSUE TITLE
Support for Location, Creature and Adventure Crafter

### ISSUE THREAD

**Issue by loofou** [saif-ellafi/foundryvtt-mythic-gme#6]
Hey,

I'm not sure this is something you planned or not (or have the right to do), but would you be inclined to provide features for the Mythic supplements for creating Creatures, Locations and Adventures? Especially the second two would be immensely interesting to non-solo games and sessions as well, as they can be used by GMs to help generate content during a session.

Just to be sure: I'm more talking about a way to keep track of the results above, less the actual rules to put in. For the Adventure Crafter that would be Plots and Scenes, etc, for the Location Crafter that would be to keep track of the three lists, as well as progressing.

Thanks for the work on this in any case :)

**Comment by saif-ellafi** [comment]
Hello @loofou - Thanks for reaching out and using the module! Ok, beware, long answer!!!

I am really interested in approaching this discussion. I have given it some thought and there are a couple of reasons I am inclined towards not supporting the Crafter Series as well as not supporting magazine specific variations. These are my current reasons:

- The license and permission request I have got, is for the Mythic books. It is feasible that Tana Pigeon could say yes, but it can also be seen as "too much" to ask. Already here I am providing copyright material in terms of tables and basic structure for Mythic.

- It is quite a lot of work, and I am a lazy developer :)

- License and Laziness topics aside, I am thinking towards a "Flexible" approach. As you might have noticed, in general, solo players or emulator approached GMs and tinkerers, tend to customize their game a lot. For this reason, in the latest releases I have been providing tools to expand on this flexibility, rather than out of the box solutions.

- I think it will pay off to be versatile with Foundry VTT and in combination of these tools, many things can be already achieved. I would be interested in hearing out, which tasks are currently not possible to do! (Without having to write code, of course)

These are some of the tools I've been adding to this module in the latest releases:

1. The Oracle Builder. With your own Random Tables in Foundry, you can setup up to 5 tables, that will be rolled sequentially. I use this to generate for example three worded oracles that require three table outcomes! It also supports for rolling more than once per table. The output is saved as a Macro and you can reuse it later.

2. The Flavored Random Table Roll, just on the last release (actually today), I have made it possible to roll up to 5 random tables you possess in Foundry, not only multiple times each, but also by overriding the formula. This, I did it with the "Progress Points" in mind, of the Location Crafter, since at first you roll `1d10` but then `1d10+1` `1d10+2`, etc, etc. So with this Macro you can roll from the "Area Elements" (A table any user can load it themselves) and quickly roll those.
![image](https://user-images.githubusercontent.com/27952699/148571651-60769d61-c05f-4464-b41c-6e1322347c4a.png)

3. The External Random Table Roll Macro, that draws a formula for you, and gives you a space for introducing the table output for that. This I created precisely because I am way too lazy to load all 5 theme-based PlotPoint tables. I roll 5 times 1d100 and ingest 
![image](https://user-images.githubusercontent.com/27952699/148571556-eab4084f-a9ad-4ef6-9d4d-24bd65822c57.png)

Having said that, if you happen to ingest your own tables into Foundry (i've heard some people did!), with these tools you can achieve quite most of it, no?

For the **Adventure Crafter**, you can create a **Themes Table**, in which each entry of the Random Table corresponds to another Random Table (The one for PlotPoints for that Theme). When rolling on the parent Random Table, Foundry will automatically draw a value from the sub-table! I haven't done this, since I am way too lazy. So I use "Roll From External Tables" to roll 5 times 1d100 and look it up on the PDF (with PDFoundry), it is not blazing fast but it is alright, depending on how frequently you pull new plotlines!

For the **Location Crafter** (I use the randomized one from Magazine 2), I have loaded the tables since they are very small into Foundry. With the Flavor Random Table Macros I can quite quickly get a new location, and override the roll formula.
![image](https://user-images.githubusercontent.com/27952699/148573350-52bfab86-6d63-4541-85db-bb86189db08e.png)

Also, feel free to be setup Foundry to your needs, my own personal setup is made by a few of my own modules:
- Window Controls (to be able to pin tables and journals, never to be closed)
- Drag anything to Hotbar (to bring  random tables to the macro hotbar for quick roll)
- I use inline chat rolls and inline table rolls a lot, for things like `there are [[1d4]] bandits` or `The theme is [[#Theme Table]]]` in the chat, and quickly roll for randomness in there
- For other Oracles like UNE Motivations, I use the Oracle Builder from this module
![image](https://user-images.githubusercontent.com/27952699/148573669-103e2749-eb21-4688-87cd-3c1c7d38c126.png)

:D Hope this makes sense, and looking forward to your thoughts!

**Comment by loofou** [comment]
Thank you for the very detailed answer.

I understand that basically most of the things you need for the Crafter tables are already provided, but I feel you would need to do too many manual changes to be able to use it in a GM-based session during play.

This is mainly a concern for the Location Crafter I guess: I usually had a google sheet that helped me with the locations during play. I would change the counter and it would randomly select another line. Trouble is: it didn't handle strike-outs (already seen) elements well and I feel the same is happening here. I also can't spend a few minutes to update all +X on the rolls manually every time the players go into another area. I was hoping for some automation towards that. I really don't want my GM helper tools to slow down game, that's why I use them in the first place (to make the game faster).

The Adventure Crafter I would probably use during session planning anyway, so for that this is less of an issue. There I would've just preferred something like a preset sheet or something, as I hate handling paper or additional pdfs on the side if I could have everything in Foundry. Maybe I write a small module myself for this one day...

But I get the lazy and the license part. It was just some hope :) Still, thank you for the good work!

**Comment by saif-ellafi** [comment]
Indeed! I will still keep my thoughts open to see of ways for improving it for fast in-game experience.
I have a game coming up soon, and maybe I will scratch my head just like you :D 

My biggest laziness is the Adventure Crafter because of the huge tables and also it comes with much customization, based on the theme setup. But would it work out if we started with the Locations Crafter and Creature Crafter (I have to buy it) @loofou

**Comment by loofou** [comment]
Oh I can absolutely understand that. I personally don't use the Adventure Creator during sessions (yet), so this is something I wouldn't want or expect soon. The Location Crafter would be my #1 request indeed, I think. Creature Crafter seems also not too complex (there it would mainly be a nice UI/dialog or output I guess).

If you ever want to look into the Adventure Crafter, I found using the Card Decks simplifies the user-centric tables (characters and plots) a lot, but yes, it's still quite some work.

Do you want me to make three separate request issues out of this, one for each Crafter system to keep better track of it? Even if you do not work on it anytime soon (or at all) it might help staying organized, unless you do not use Github issues for task tracking :)

**Comment by loofou** [comment]
I actually don't own the magazines, so I only know the regular one. But yes, I usually spend around 30 minutes preparing the tables and that is fine with me. I just want to avoid having to adjust the tables manually during the session. But maybe interpretation of random events is good enough for now. I will grab the magazine and see how it works there.

Thanks!

**Comment by saif-ellafi** [comment]
@loofou I have made a prototype of the magazine version! (The one I have). Take a look. The tables are not included however. The Progress points are managed like chaos, and with Nested Random Tables, the special and random elements work fine.

**Comment by loofou** [comment]
Great! I will take a look as soon as I find the time :)

Btw: I created the split issues for each of the features. It's only for the simplified versions for now, with assessment of feasibility of the full versions at a later point (it's just great to have something at this point :) ). I guess we can close this issue then?

**Comment by saif-ellafi** [comment]
Thanks!
